#  * -*  *- *- *- *- *- *- * * ** -* -* -* - *- *- *-* - ** - *- - * *-   #
#  *       _                                 _                        +\  #
#   -     | |_ ___ ___ ___ ___ ___ ___ ___ _| |___ ___ ___ ___       +    #
#   +     |  _|  _| .'|   |_ -|  _| -_|   | . | -_|   |  _| -_|       /*  #
#  *      |_| |_| |__,|_|_|___|___|___|_|_|___|___|_|_|___|___|         + #
#  -       ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~        *  #
#  *       Oscar Kruithof   |   okruitho    |   Alpha_1337k           *-  #
#  -*      Robijn van Houts |   rvan-hou    |   robijnvh             -+   #
#  * /   Jonas Bennink Bolt |   jbennink    |   JonasDBB            /-    #
#  /       Tim van Citters  |   tvan-cit    |   Tjobo-Hero           *    #
#   +      Rene Braaksma    |   rbraaksm    |   rbraaksm              -   #
#    *.                                                              ._   #
#   *.   dockerfile               | Created: 2021-10-26 22:33:59    ._    #
#  -     Edited on 2021-10-26 22:33:59 by alpha                      .-   #
#  -* *- *- * -* -* -* ** - *-* -* * /  -* -*- * /- - -* --*-*++ * -* *   #
FROM node:16.10

WORKDIR /serv
EXPOSE 80
ENTRYPOINT "./entrypoint.sh"