version: "3.3"
services:
  web:
    build: .
    volumes:
      - "./src:/serv"
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: codam
      POSTGRES_DB: test
